title:
author:
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anivaros.dev" # the base hostname & protocol for your site, e.g. http://example.com
favicon: /assets/favicon-anivaros
og_image: /assets/og-anivaros
twitter_image: /assets/twitter-anivaros
lang: ru
language_default: ru
timezone: UTC+3
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - changes.md

# Social media
twitter_username: anivaros
google_tag: G-PPWKGCQT6T
yandex_metrika: 90115187

# Plugins
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-last-modified-at

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /:year/:month/:day/:title/

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# jekyll-multiple-languages-plugin settings:
languages: ["ru", "en"]
exclude_from_localizations: ["assets", "robots.txt", "CNAME"]
